export const empresas = [
     {
          id: 1,
          nome: "Fomenta Vale",
          cnpj: "7458-9856-2013",
          email: "contato@fomentavale.com.br",
          endereco: "Rua Nove de Julho - 106",
          descricao: "Tecnologia",
          parceira: "SIM",
     },
     {
          id: 2,
          nome: "Lacottick",
          cnpj: "1245-9856-2580",
          email: "lacottick@contato.com.br",
          endereco: "Avenida Rui Barbosa - 1010",
          descricao: "Desenvolvimento de Jogos",
          parceira: "SIM",
     },
     {
          id: 3,
          nome: "Felamps street",
          cnpj: "8520-9875-0134",
          email: "contato@felamps.com.br",
          endereco: "Avenida Rui Barbosa - 510",
          descricao: "Roupas",
          parceira: "Não",
     },
     {
          id: 4,
          nome: "Casa di Conti",
          cnpj: "1234-5678-9101",
          email: "contato@casadiconti.com",
          endereco: "Avenida dos Mangues - 980",
          descricao: "Alimentos",
          parceira: "SIM",
     },
     {
          id: 5,
          nome: "Casa Avenida",
          cnpj: "7410-8520-9630",
          email: "contato@casaavenida.com.br",
          endereco: "Distrito industrial - Rua Amidala - 108",
          descricao: "Supermercado",
          parceira: "SIM",
     },
     {
          id: 6,
          nome: "Duaço empreendimentos",
          cnpj: "1234-4567-7891",
          email: "contato@duaco.com.br",
          endereco: "Avenida dos Mangues - 847",
          descricao: "Construção",
          parceira: "NÃO",
     },{
          id: 7,
          nome: "Fomenta Vale",
          cnpj: "7458-9856-2013",
          email: "contato@fomentavale.com.br",
          endereco: "Rua Nove de Julho - 106",
          descricao: "Tecnologia",
          parceira: "SIM",
     },
     {
          id: 8,
          nome: "Lacottick",
          cnpj: "1245-9856-2580",
          email: "lacottick@contato.com.br",
          endereco: "Avenida Rui Barbosa - 1010",
          descricao: "Desenvolvimento de Jogos",
          parceira: "SIM",
     },
     {
          id: 9,
          nome: "Felamps street",
          cnpj: "8520-9875-0134",
          email: "contato@felamps.com.br",
          endereco: "Avenida Rui Barbosa - 510",
          descricao: "Roupas",
          parceira: "Não",
     },
     {
          id: 10,
          nome: "Casa di Conti",
          cnpj: "1234-5678-9101",
          email: "contato@casadiconti.com",
          endereco: "Avenida dos Mangues - 980",
          descricao: "Alimentos",
          parceira: "SIM",
     },
     {
          id: 11,
          nome: "Casa Avenida",
          cnpj: "7410-8520-9630",
          email: "contato@casaavenida.com.br",
          endereco: "Distrito industrial - Rua Amidala - 108",
          descricao: "Supermercado",
          parceira: "SIM",
     },
     {
          id: 12,
          nome: "Duaço empreendimentos",
          cnpj: "1234-4567-7891",
          email: "contato@duaco.com.br",
          endereco: "Avenida dos Mangues - 847",
          descricao: "Construção",
          parceira: "NÃO",
     }
]